# Generated by Django 4.0.4 on 2022-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_notife', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='message',
            name='unique_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
