# Generated by Django 4.0.4 on 2022-05-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_notife', '0003_alter_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='unique_id',
        ),
    ]
