# Generated by Django 4.0.4 on 2022-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_notife', '0004_alter_mailing_options_remove_client_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='tag',
            field=models.TextField(default=1, verbose_name='Тэг'),
            preserve_default=False,
        ),
    ]
